version: 2
updates:
  # for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"                                                                   # `package.json` の場所
    schedule:
      interval: "weekly"                                                             # チェック頻度を週次に設定
    target-branch: "develop"                                                         # マージ先のブランチを `develop` に指定
    allow:                                                                           # 依存関係のチェックを許可するパッケージ
      - dependency-name: "astro"
      - dependency-name: "contentful"
      - dependency-name: "daisyui"
      - dependency-name: "tailwindcss"
      - dependency-name: "typescript"
      - dependency-name: "@biomejs/biome"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]                                # メジャーバージョンの更新は週次で無視
    commit-message:
      prefix: "chore"
    rebase-strategy: "auto"

  # for Dockerfile
  - package-ecosystem: "docker"
    directory: "/.devcontainer/docker/web/"                                          # `Dockerfile` の場所
    schedule:
      interval: "weekly"                                                             # チェック頻度を週次に設定
    target-branch: "develop"                                                         # マージ先のブランチを `develop` に指定
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]                                # メジャーバージョンの更新は週次で無視
    commit-message:
      prefix: "chore"
    rebase-strategy: "auto"
