services:
  astro-web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    tty: true
    environment:
      - NODE_ENV=${NODE_ENV}
      - CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE_ID}
      - CONTENTFUL_TOKEN=${CONTENTFUL_TOKEN}
    ports:
      - 4321:4321
    volumes:
      - ../:/service/web/my-homepage
